# Generated by Codex on 2026-04-25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.URLField(blank=True, verbose_name="imagem de capa"),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, max_length=255, verbose_name="resumo"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="destaque"),
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="publicado em",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="conteudo"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True, verbose_name="publicado"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="titulo"),
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_featured", "-published_at", "-created_at"],
                "verbose_name": "publicacao",
                "verbose_name_plural": "publicacoes",
            },
        ),
    ]
